version: "3"
services:
  app:
    build:
      context: .
      target: python
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
